// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIC1sPcepLp_EOgQlt1YFCflSpyzZS2d0',
    appId: '1:81337669726:web:3162667a16b4b654d7fccf',
    messagingSenderId: '81337669726',
    projectId: 'edgefly-academy-9b88f',
    authDomain: 'edgefly-academy-9b88f.firebaseapp.com',
    storageBucket: 'edgefly-academy-9b88f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxJdRdMYeBd6fhgiv-TM0XLZ9swMBMIzk',
    appId: '1:81337669726:android:23b35f04c171f59cd7fccf',
    messagingSenderId: '81337669726',
    projectId: 'edgefly-academy-9b88f',
    storageBucket: 'edgefly-academy-9b88f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFAul-b6J78zJEdRsaPLzoypSEdiCvRkQ',
    appId: '1:81337669726:ios:503b8d110adff2f6d7fccf',
    messagingSenderId: '81337669726',
    projectId: 'edgefly-academy-9b88f',
    storageBucket: 'edgefly-academy-9b88f.appspot.com',
    androidClientId: '81337669726-2m4o04kipm7mq0vjfjvhdtc4aibejqqf.apps.googleusercontent.com',
    iosClientId: '81337669726-hp90nubggu84b3474ip2fqv05752m5mo.apps.googleusercontent.com',
    iosBundleId: 'com.example.edgeflySuperAdmin',
  );
}
